### ISSUE TITLE
Unable connect with wsEndPoint transfered via file

### ISSUE THREAD

**Issue by sukrosono** [puppeteer/puppeteer#1123]
### Steps to reproduce
[here the script](https://github.com/brutalcrozt/puppeteer/tree/dev-enter/examples/connect)
1. run script 1 to store wsEndPoint to a file.
1. run script 2 to try connect existing browser with wsEndPoint from step 1.

**Tell us about your environment:**

* Puppeteer version: `0.13.0 beta`
* Platform / OS version: `windows 8`

**What is the expected result?**
- [ ] Able to connect to existing browser.
- [ ] Proper message at least.

**What happens instead?**
```
(node:15252) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Parameter "url" must be a string, not undefined
```

#### Out of Context
i just facing this when trying answer this [SO question](https://stackoverflow.com/questions/46805679/how-to-remain-chromium-opened-using-puppeteer)

**Comment by xprudhomme** [comment]
You are most likely getting issues with your code when reading data from the file and/or writing in it. I have implemented my own solution and it works perfectly (i.e. it has nothing to do with Puppeteer if your code does not work).

Here is a code sample from my own lib (assume we are in an object context):

```

      // Save session to file
      await saveToJSONFile({endpoint: browser.wsEndpoint(), "session.json").then(file => {
          console.log("Websocket endpoint JSON has been succesfully saved to %s", file)
      });

      /**
       * Write JSON object to specified target file
       * @param {String} jsonObj 
       * @param {String} targetFile 
       */
      async saveToJSONFile(jsonObj, targetFile) {

        if( !/^\//.test(targetFile) )
          targetFile = this._jsonsPath + targetFile;
        
        if(!/\.json$/.test(targetFile))
          targetFile+= ".json";

        return new Promise((resolve, reject) => {

          try {
            var data = JSON.stringify(jsonObj);
            console.log("Saving object '%s' to JSON file: %s", JSON.stringify(jsonObj, null, 2), targetFile);
          }
          catch (err) {
            console.log("Could not convert object to JSON string ! " + err);
            reject(err);
          }
            
          // Try saving the file.        
          fs.writeFile(targetFile, data, (err, text) => {
            if(err)
              reject(err);
            else {
              resolve(targetFile);
            }
          });
          
        });
      }


     /**
      * Retrieve a websocket url and resume existing session
      * @param {string} file 
      */
      async resumeSessionFromFile(file) {

        var setSession = (wsEndpointObj) => {
          console.log("Connecting to websocket endpoint: ", wsEndpointObj.endpoint );
          return puppeteer.connect({browserWSEndpoint: wsEndpointObj.endpoint});
        };

        return this.getFileContents(file).then(setSession).then((browser)=>{
          console.log("Successfully connected to previous session, using websocket URL from file '"+file+"' !");
          return browser;
        });
      }


     /**
      * Retrieve a file contents, as a text string or a JSON object if the string is JSON formatted
      * @param {string} file 
      */
      async getFileContents(filename) {

        return new Promise((resolve, reject) => {

          fs.readFile(filename, (err, data) => {

              if (err) 
                  reject(err); 
              else {

                console.log("Getting contents from file: %s", filename );

                var jsondata = false;

                // Test data, if it's a JSON object or just a string
                try {
                  jsondata = JSON.parse(data);
                }
                catch(err) {
                  console.log("Data is not in JSON format");
                }

                if(Object(jsondata)===jsondata) {
                  console.log("Data is: " + JSON.stringify(jsondata, null, 2));
                  resolve(jsondata);
                }
                else {
                  console.log("Data is: " + data);
                  // Data passed is a buffer, not a string (when not specifying the encoding)
                  resolve(data.toString());
                }
              }
          });
        });
      }
```

**Comment by sukrosono** [comment]
Thanks @Xavatar , but i still face same error:
![image](https://user-images.githubusercontent.com/3001652/32147640-276a52da-bd1d-11e7-9dc9-a34191cb7c5b.png)


i already push your code into my branch, let me know if you found my mistake.
Can you describe your environment? Mine is:
```
  puppeteer lastest from master
  Os: win 8, 64 bit
  Node:  7.6.0
```
Idk what else is related.

**Comment by xprudhomme** [comment]
I've edited my previous message and added a missing piece of code:

`      // Save session to file
      await saveToJSONFile({endpoint: browser.wsEndpoint(), "session.json").then(file => {
          console.log("Websocket endpoint JSON has been succesfully saved to %s", file)
      });`

This is how you save the current browser websocket endpoint URL into a JSON file.

My environment is Ubuntu 16.04 LTS, Node 8.8.1, Puppeteer 0.11.0

But without any piece of code from your side, no one will be able to help you ..

**Comment by sukrosono** [comment]
My goal is only to connect running chromium using puppeteer. Thank @Xavatar you are correct, it's my mistake on handle the promise.
