### ISSUE TITLE
[Bug]: Table header overlap issue in generated pdf (if there is other elements in html template and the content in row is long and the table in multiple pages)

### ISSUE THREAD

**Issue by KelongShi-prospa** [puppeteer/puppeteer#11493]
### Minimal, reproducible example

```TypeScript
you can download/access this public repo to reproduce the issue: https://github.com/KelongShi-prospa/puppeteer-pdf-layout-issue-for-mutiple-page-table
```

### Error string

no error

### Bug behavior

- [ ] Flaky
- [X] PDF

### Expectation

the table header & content should not overlap.

### Reality

![image](https://github.com/puppeteer/puppeteer/assets/107183442/c2adb357-1f22-4680-89b1-17d2b29a9f52)

### Puppeteer version

13.7.0

### Node version

v16.13.2

### Package manager

npm

### Package manager version

8.1.0

### Operating system

macOS

**Comment by KelongShi-prospa** [comment]
Close this one because it has been fixed in the latest puppeteer

**Comment by bradytrudeau** [comment]
@KelongShi-prospa do you mind sharing your configuration for this? I'm experiencing the same issue that you were experiencing and just finished upgrading to v22, but am still experiencing this issue. Any insight would be super helpful! Thanks!
