### ISSUE TITLE
Chrome for Testing downloads via edgedl.me.gvt1.com are failing

### ISSUE THREAD

**Issue by OrKoN** [puppeteer/puppeteer#11987]
Hi everyone,

Currently, the edgedl endpoint providing Chrome for Testing downloads is not working properly. It is expected to be back soon so if you can wait please retry downloading later. I will update this issue once the https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/ endpoints work again.

These URLs are not used by the latest versions of Puppeteer and `@puppeteer/browsers` so it affects the following versions:

1) `puppeteer<v22.2.0`
2) `@puppeteer/browsers<v2.0.1` 

If you are unable to update the version as a workaround, you could reconfigure old versions to use `https://storage.googleapis.com/chrome-for-testing-public/` as the `downloadBaseUrl` (for example, by setting the environment variable `PUPPETEER_DOWNLOAD_BASE_URL="https://storage.googleapis.com/chrome-for-testing-public/"` or changing the puppeteer [config file](https://pptr.dev/guides/configuration)).

Please do not file new issues for this problem.

**Comment by OrKoN** [comment]
It looks like endpoints started to recover. I will double check tomorrow again.

**Comment by kevindurley** [comment]
@OrKoN ... just re-deployed and it's working again - phew!

**Comment by OrKoN** [comment]
I have tested again today and it looks like the issue has been resolved.

**Comment by cjroebuck** [comment]
Are the links down again? Getting a 404 for the following command:

```
npx  @puppeteer/browsers install chrome

Error: Download failed: server returned code 404. URL: https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/123.0.6312.10/mac-x64/chrome-mac-x64.zip
```

**Comment by pei-wang** [comment]
Hi @OrKoN ,
It seems broken again. I am still having the issue. could u please have a look?

**Comment by OrKoN** [comment]
It looks like the browsers package is not the latest version: `npx @puppeteer/browsers@latest install chrome`. Or use `PUPPETEER_DOWNLOAD_BASE_URL=https://storage.googleapis.com/chrome-for-testing-public` with an older version of the browsers CLI.
