### ISSUE TITLE
[Bug]: Headers not getting updated using page.setRequestInterception(true) for firefox

### ISSUE THREAD

**Issue by shukrash** [puppeteer/puppeteer#14333]
### Minimal, reproducible example

```TypeScript
import puppeteer from "puppeteer-core";

export async function try() {
  const browser = await puppeteer.launch({
    browser: 'firefox',
    executablePath: '/tmp/browser/firefox/firefox'
  });

  const page = await browser.newPage();
  await page.setRequestInterception(true);

  page.on("request", request => {
    const headers = request.headers() || {};
    headers['testung'] = 'abceded';
    console.log(`[request] ${JSON.stringify(headers)}`);
    request.continue({ headers });
  });

  page.on('response', response => {
    console.log(`[response] ${response.status()} ${JSON.stringify(response.request().headers())}`);
  });

  const response = await page.goto("https://support.mozilla.org");
  await browser.close();
}

export async function handler() {
  return await try();
};
```

### Background

I am trying to add additional headers to requests made during page load.
I am using setRequestInterception. 
In the above code, when I print the headers before request continue, the headers have the new headers. However, the request object in response does not.

[request] {\"host\":\"location.services.mozilla.com\",\"user-agent\":\"Mozilla/5.0 (X11; Linux x86_64; rv:141.0) Gecko/20100101 Firefox/141.0\",\"accept\":\"*/*\",\"accept-language\":\"en-US,en;q=0.5\",\"accept-encoding\":\"gzip, deflate, br, zstd\",\"referer\":\"https://support.mozilla.org/\",\"origin\":\"https://support.mozilla.org\",\"connection\":\"keep-alive\",\"sec-fetch-dest\":\"empty\",\"sec-fetch-mode\":\"cors\",\"sec-fetch-site\":\"cross-site\",\"testung\":\"abceded\"

[response] 200 {\"host\":\"location.services.mozilla.com\",\"user-agent\":\"Mozilla/5.0 (X11; Linux x86_64; rv:141.0) Gecko/20100101 Firefox/141.0\",\"accept\":\"*/*\",\"accept-language\":\"en-US,en;q=0.5\",\"accept-encoding\":\"gzip, deflate, br, zstd\",\"referer\":\"https://support.mozilla.org/\",\"origin\":\"https://support.mozilla.org\",\"connection\":\"keep-alive\",\"sec-fetch-dest\":\"empty\",\"sec-fetch-mode\":\"cors\",\"sec-fetch-site\":\"cross-site\"}

### Expectation

Request headers in response to contain the new custom header

### Reality

Request headers in response do not contain the new custom header

### Puppeteer configuration file (if used)

```TypeScript

```

### Puppeteer version

24.15.0

### Node version

22.x

### Package manager

npm

### Package manager version

11.6.2

### Operating system

Linux

**Comment by shukrash** [comment]
I tried adding priority request.continue({ headers }, 10); that does not help

**Comment by OrKoN** [comment]
Thanks for reporting but request headers are separate from response headers. Puppeteer only supports request interception and not response interception. The response headers are provided by the server in this. The behavior seems to be as expected.

**Comment by shukrash** [comment]
@OrKoN : But these are request headers in response! response.request().headers() ... These would indicate the headers with which the request reached the server.

**Comment by OrKoN** [comment]
Sorry, misunderstood! But the reason for the behavior is that you are mutating the original object returned by `request.headers()` and modify the internal state of the headers. In Firefox, which relies on WebDriver BiDi, headers come from multiple sources and therefore each call to `.headers()` gives a copy of the underlying data. This mutation is not meant to update the underlying headers so we will fix the issue for Chrome.

**Comment by OrKoN** [comment]
Related and probably a duplicate of this issue https://github.com/puppeteer/puppeteer/issues/4165

**Comment by shukrash** [comment]
@OrKoN : I would like to clarify that this issue is on firefox! Chrome works perfectly for this scenario!
Heres the log by replacing chrome in the above script:
[request] {\"upgrade-insecure-requests\":\"1\",\"user-agent\":\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/140.0.7339.185 Safari/537.36\",\"sec-ch-ua\":\"\\\"Chromium\\\";v=\\\"140\\\", \\\"Not=A?Brand\\\";v=\\\"24\\\", \\\"HeadlessChrome\\\";v=\\\"140\\\"\",\"sec-ch-ua-mobile\":\"?0\",\"sec-ch-ua-platform\":\"\\\"Linux\\\"\",\"accept\":\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\",\**"testung\":\"abceded\"**}

[response] 302 {\"upgrade-insecure-requests\":\"1\",\"user-agent\":\"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/140.0.7339.185 Safari/537.36\",\"sec-ch-ua\":\"\\\"Chromium\\\";v=\\\"140\\\", \\\"Not=A?Brand\\\";v=\\\"24\\\", \\\"HeadlessChrome\\\";v=\\\"140\\\"\",\"sec-ch-ua-mobile\":\"?0\",\"sec-ch-ua-platform\":\"\\\"Linux\\\"\",\"accept\":\"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7\",**\"testung\":\"abceded\"**}

**Comment by shukrash** [comment]
Also, _This mutation is not meant to update the underlying headers_ Does this mean there is no way to add extra headers to intercepted requests? Eg tracing headers etc?
Its also documented here as the way to go: https://hacks.mozilla.org/2024/08/puppeteer-support-for-firefox/

**Comment by shukrash** [comment]
@OrKoN : Can we reopen this for firefox?

**Comment by OrKoN** [comment]
You can change headers on the request with interception, but it is not expected to update the data in request.headers() that is created before the interception happens. The PR https://github.com/puppeteer/puppeteer/pull/14341 aligns the behavior between both browsers by fixing the issue.

**Comment by shukrash** [comment]
So, the command:
_request.continue({ headers });_
will send the new headers to server? It will just not be present in the request object in the response since the headers are not mutable?

**Comment by OrKoN** [comment]
> will send the new headers to server? It will just not be present in the request object in the response since the headers are not mutable?

correct

**Comment by shukrash** [comment]
I tried request interception in playwright to update headers, it behaves in the way older chrome interception worked! I am not sure whether removing the feature from Chrome should be the fix for this? 

Also, in the context of the updated headers making it to the server, this is more confusing. So, we are essentially creating a separate request object (intercepted request object with modified headers) that makes it to the server? Other wise how will the server get the updated headers?

**Comment by OrKoN** [comment]
The `request.continue({ headers });` sends a [continueRequest](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-continueRequest) call that accepts all headers to be set on the actual request (this happens on the browser side). Puppeteer's `request.headers()` is the state of the headers before the request continues. `response.request()` and `request` are the same object so it makes sense that headers are the same (https://github.com/puppeteer/puppeteer/issues/4165 confirms that).

There are situations where multiple consumers use request interception API (https://pptr.dev/guides/network-interception#multiple-intercept-handlers-and-asynchronous-resolutions). In that case, allowing each consumer to mutate the underlying object before the request continues could lead to unexpected results because some consumer would see the data changed by other consumers and not the headers coming from the browser originally. 

So instead of this:

```
page.on("request", request => {
    const headers = request.headers() || {};
    headers['testung'] = 'abceded';
    console.log(`[request] ${JSON.stringify(headers)}`);
    request.continue({ headers });
  });
```

you can do

```
const modifiedHeaders = new WeakMap();
page.on("request", request => {
    const headers = request.headers() || {};
    headers['testung'] = 'abceded';
    console.log(`[request] ${JSON.stringify(headers)}`);
    modifiedHeaders.set(request, headers);
    request.continue({ headers });
});

page.on('response', response => {
   const headers = modifiedHeaders.get(response.request());
    console.log(headers);
});
```

https://github.com/puppeteer/puppeteer/issues/4165 indicates that it is not expected that `response.request().headers()` contain modified headers. If https://github.com/puppeteer/puppeteer/issues/4165 is fixed, it should be updating headers internally based on the data passed to continue and not based on the mutation `headers['testung'] = 'abceded';`. Just consider the following example:

```
  page.on("request", request => {
    const headers = request.headers() || {};
    headers['testing'] = 'abceded';
    console.log(`[request] ${JSON.stringify(headers)}`);
    request.continue({ headers: {differentHeaders: 'test'} });
  });

  page.on('response', response => {
    console.log(`[response] ${response.status()} ${JSON.stringify(response.request().headers())}`);
  });
```

It clearly demonstrates that this is a bug in interception for Chrome since `response.request().headers()` would include the testing when the request was not continued with it.

**Comment by shukrash** [comment]
I think I misunderstood the concern.. we are actually sending the modified object into the request.continue().
So.. in the above example.. would you expect "differentHeaders" to be present in response.request().headers()?

**Comment by OrKoN** [comment]
No, `differentHeaders` are currently not expected to be in `response.request().headers()` (which holds the headers as received before interception). Also, in that example, the testing header is also not expected to be in ` response.request().headers()` (fixed as part of this issue). This feature request https://github.com/puppeteer/puppeteer/issues/4165 tracks adding support for `differentHeaders` to indeed update the `response.request().headers()` but it should be done based on the headers supplied to `continue()` (considering cooperative request interception mode).

**Comment by shukrash** [comment]
Is there an ETA for https://github.com/puppeteer/puppeteer/issues/4165 ? Because this change will break production functionality for us. In absence of any parameter in request that uniquely identifies it, it is impossible to map a request to response with 100 % confidence!

**Comment by OrKoN** [comment]
You can use a weak map to uniquely identify a request like in the example I provided https://github.com/puppeteer/puppeteer/issues/14333#issuecomment-3449858151

**Comment by shukrash** [comment]
but that wont differentiate 2 requests to the same end point with same params?

**Comment by OrKoN** [comment]
Each request object is unique and weak map uses object identity to keep track of the data. Do you have an example of where you think it would not work?

**Comment by shukrash** [comment]
How about a request retry? For eg. I have a Get API.. first call to it fails with 5xx... second call passes.. I need to be able to tell the two apart!

**Comment by OrKoN** [comment]
Each retry is a new request in the browser.

**Comment by OrKoN** [comment]
Coincidentally https://github.com/puppeteer/puppeteer/issues/4165 was just fixed and will be available in the next release.

**Comment by shukrash** [comment]
hmm.. the fix for 4165 is not updating the puppeteer request object though! So the request object coming back in response will still not have the updated headers mentioned in request.continue!
