### ISSUE TITLE
page content incorrectly embedded when using file protocol

### ISSUE THREAD

**Issue by pocketjoso** [puppeteer/puppeteer#1506]
Hi again,
As usual, thanks a lot for maintaining puppeteer - it's super useful. 👍 

Seems to me that there was a regression in `0.13` 🐛  when using the combination of:
- `file:///` protocol
- `setRequestInterception: true`

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: `0.13.0`
* Platform / OS version: `MacOS High Sierra`, same on `windows`
* URLs (if applicable):
Any url over the `file` protocol seems to have this problem.

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._
```js
const puppeteer = require('puppeteer');
(async() => {
const browser = await puppeteer.launch({
      // waitUntil: 'networkidle2', // see if this performs better than default for timeouts
      ignoreHTTPSErrors: true,
      args: ['--disable-setuid-sandbox', '--no-sandbox']
    })
const page = await browser.newPage()

// CRITICAL: _only_ with setRequestInterception = true do we get this problem:
// the real html is escaped and embedded in a template like below.
// <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">
// <REAL CONTENT HERE>
// </pre></body></html>
await page.setRequestInterception(true)
page.on('request', interceptedRequest => {
  console.log(interceptedRequest.url)
  interceptedRequest.continue()
})

// ANY local html file will do
await page.goto('file:///Users/pocketjoso/penthouse/test/static-server/yeoman.html')

const content = await page.content()
console.log('content: ' + content)

browser.close();
})();

```
**What is the expected result?**
The html is parsed in the same way regardless of file/http protocol, and regardless of whether `setRequestInterception` is true or false. 

**What happens instead?**
```
content: <html><head></head><body><pre style="word-wrap: break-word; white-space: pre-wrap;">&lt;!doctype html&gt;
&lt;html class="no-js"&gt;
    &lt;head&gt;
        &lt;meta charset="utf-8"&gt;
        &lt;title&gt;critical css test&lt;/title&gt;
        &lt;meta name="description" content=""&gt;
        &lt;meta name="viewport" content="width=device-width, initial-scale=1"&gt;
        &lt;!-- Place favicon.ico and apple-touch-icon.png in the root directory --&gt;
... etc
```
Or in a picture (the browser renders the markup as text, rather than as html):
![bjor6laez-after](https://user-images.githubusercontent.com/7192832/33457425-be84ce3e-d622-11e7-8d43-41c96a3ac35f.jpg)

**Comment by jimmo** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=791439

**Comment by Saturate** [comment]
The real issue is reported here and is assigned, let's hope its fixed soon: https://bugs.chromium.org/p/chromium/issues/detail?id=781133

**Comment by Saturate** [comment]
This has been fixed in chromium version `536395` confirmed on a Windows 8.1 machine, and a Windows 10 machine.

Can't reproduce this error anymore! :tada: 

https://bugs.chromium.org/p/chromium/issues/detail?id=781133#c14

**Comment by pocketjoso** [comment]
Awesome, so a future release of Puppeteer should have this issue resolved then. 🎉

**Comment by pocketjoso** [comment]
Just tested this thoroughly now, and unfortunately this issue came back in `Puppeteer@1.1.0`... :/

✅ Puppeteer@0.12.0 Worked
❌ Puppeteer@0.13.0 broke Penthouse due to the file:// protocol issue.
✅ Puppeteer@1.0.0 made it work again
❌ Puppeteer@1.1.0 broke again..
❌ Puppeteer@1.1.1 same..
_Update:_
❌ Puppeteer@1.2.0 still broken

If this is purely related to the Chromium bug (https://bugs.chromium.org/p/chromium/issues/detail?id=781133#c14), and the puppeteer changelog is correct, then:

✅Chromium 65.0.3312.0 (r526987), introduced in `1.0.0` (fixed this issue)
❌Chromium 66.0.3348.0 (r536395), introduced in `1.1.0` (broke it again)
_Update:_
❌Chromium 67.0.3372.0 (r543305), introduced in `1.2.0` (still broken)

Will upgrade Penthouse to `1.0.0` now but it's a shame not being able to be on the latest version... Any insights on how Chromium releases are cut and if there's a possibility the `66.0.3348` version somehow missed to take up the fix that `65.0.3312.0` contained?

**Comment by Saturate** [comment]
Wauw, great work but what a nightmare.

**Comment by pocketjoso** [comment]
Just tested with `Puppeteer@1.2`, `Chromium 67.0.3372.0 (r543305)` and it is still broken. :/

**Comment by aslushnikov** [comment]
@pocketjoso I'm testing on OS X, and Chrome r526987 doesn't seem to work for me. pptr@1.0.0 didn't work as well.

Looks like this was permanently broken for us

**Comment by pocketjoso** [comment]
That's strange because I'm on MacOS as well and it does work in latest [Penthouse](https://github.com/pocketjoso/penthouse/), which uses Puppeteer@1.0.0, which should be using Chromium 65.0.3312.0 (r526987).

**Comment by aslushnikov** [comment]
For the record: upstream fix for this has landed as https://crrev.com/550319
This will be fixed with the upcoming chromium roll.

**Comment by pocketjoso** [comment]
That's great! 👏 Any insight into how it fell out of Chromium between the different versions, just a regression of some sort?

If possible please ping here on the next Puppeteer release where Chrome is bumped, then we can hopefully close this and move on (move everyone to latest Puppeteer) 💯

**Comment by ValentinFunk** [comment]
@pocketjoso the changes above seem to have been released now in puppeteer v1.4.0, does this make it possible to upgrade in https://github.com/pocketjoso/penthouse/pull/234? I was just looking into this again after experiencing the bug a few months ago, with it finally out of the way i'd be celebrating so hard :tada:

**Comment by pocketjoso** [comment]
@Kamshak Yes! 🙌 Please ping the author of that PR to update, or if he is not responsive, feel free to make your own!
