### ISSUE TITLE
page.on('request') doesn't take header overrides into account when processing redirects (301/302)

### ISSUE THREAD

**Issue by Glennvd** [puppeteer/puppeteer#1664]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 0.13
* Platform / OS version: any
* URLs (if applicable): https://try-puppeteer.appspot.com/

**What steps will reproduce the problem?**
```
const browser = await puppeteer.launch();

const page = await browser.newPage();
await page.setRequestInterception(true);
page.on('response', (response) => {
  console.log('RESPONSE RECEIVED');
  console.log(response.status + ' ' + response.url);
});
page.on('request', (request) => {
 console.log('REQUEST RECEIVED');
  console.log(request.url);

  request.continue({headers: {'test-header': 'dummy-value'}});
});

await page.goto('http://www.mocky.io/v2/5a427066300000821d709e0f');
//await page.goto('https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending');

await page.screenshot({path: 'screenshot.png', fullPage: true});

await browser.close();
```
I've included the following minimal puppeteer code and 2 sample urls. https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending which is a basic page that returns the HTTP headers sent in the request.
And http://www.mocky.io/v2/5a427066300000821d709e0f which returns a 302 to the url specified above.

**What is the expected result?**
Puppeteer should send my custom header in both cases.

**What happens instead?**
Puppeteer doesn't send the custom header in the request that follows the 301/302. Even though the onRequest event is fired for both the 301 request and the followup request.

**Comment by yujiosaka** [comment]
@Glennvd 

I found your report very interesting because it can be reproduced even without puppeteer.
I implemented an example with [chrome-launcher](https://github.com/GoogleChrome/chrome-launcher) and [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface), which reproduces exactly the same result.
```
const chromeLauncher = require('chrome-launcher');
const CDP = require('chrome-remote-interface');

const TARGET_URL = 'http://www.mocky.io/v2/5a427066300000821d709e0f';
// const TARGET_URL = 'https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending';

async function main() {
  const chrome = await chromeLauncher.launch({
    chromePath: '/Users/yujiosaka/work/puppeteer/.local-chromium/mac-524617/chrome-mac/Chromium.app/Contents/MacOS/Chromium',
    startingUrl: 'target:brank',
    chromeFlags: ['--headless', '--disable-gpu'],
  });
  CDP({ port: chrome.port }, async (client) => {
    const { Network, Page } = client;
    await Promise.all([
      Network.setRequestInterception({ patterns: [{ urlPattern: '*' }] }),
      Network.enable(),
      Page.enable(),
    ])

    let requestId;
    Network.requestIntercepted(event => {
      Network.continueInterceptedRequest({
        interceptionId: event.interceptionId,
        headers: {'test-header': 'dummy-value'},
      });
    });
    Network.responseReceived(event => {
      if (event.response.url === 'https://www.whatismybrowser.com/detect/what-http-headers-is-my-browser-sending') {
        requestId = event.requestId;
      }
    });
    await Page.navigate({url: TARGET_URL});
    await Page.loadEventFired();

    const { body } = await Network.getResponseBody({ requestId });
    const isHeaderModified = /dummy-value/.test(body);
    console.log(`isHeaderModified: ${isHeaderModified}`);

    await client.close();
    await chrome.kill();
  });
}

main();
```

This means that it's not a puppeteer's bug, but probably a Chromium's bug.
I don't find a similar report in [Chromium's issue tracker](https://bugs.chromium.org/p/chromium/issues/list), so you should create one :)

**Comment by Glennvd** [comment]
I wasn't 100% sure in which category the bug belongs, but I've submitted an issue [here](https://bugs.chromium.org/p/chromium/issues/detail?id=797733).

**Comment by aslushnikov** [comment]
Thanks @Glennvd @yujiosaka for the investigation!

**Comment by schelkun** [comment]
https://github.com/GoogleChrome/puppeteer/issues/1467 ?

**Comment by 0x3E6** [comment]
@aslushnikov 
My doubts are very much like the title description.
puppeteer version: 0.13.0
OS: ubuntu 17.10
The problem is:
Manually operate the browser:
(0)browser: click `<a>`, browser send a `POST` request;
(1)server: return a response with status code 302;
(2)browser: `GET` redirected url;

However, in `page.on('request')` of puppeteer:
a. Don't call `setRequestInterception(true)`:
(0)browser: click `<a>`, browser send a `POST` request(can't get `postData`, so I give up using this way);
(1)server: return a response with status code 302;
(2)browser: `GET` redirected url;

b.Called `setRequestInterception(true)`;
(0)browser:click `<a>`, browser send a `POST` request;
(1)server:return a response with status code 302;
(2)browser: `POST`(**wrong method**) request to access redirected url;

**Comment by 0x3E6** [comment]
@aslushnikov 
The code just like this:
```JavaScript
const puppeteer = require('puppeteer');
var url = 'http://218.60.147.62/xmglgs/ListView.aspx?pl=NPZP';
var xpath = '/html/body[1]/form[1]/div[3]/div[2]/div[1]/table[1]/tbody[1]/tr[10]/td[1]/a[1]';
var browser;
var page;
var start_record = false;
var o = '>>>>>>>>>>>>>>>>>>>>>>>>>>';
var i = '<<<<<<<<<<<<<<<<<<<<<<<<<<';
(async () => {
    browser = await puppeteer.launch({
        headless: false,
    });
    page = (await browser.pages())[0];
    await page.setRequestInterception(true);
    page.on('console', msg => console.log('PAGE LOG:', msg.text));
    page.on('request', request => {
        if (start_record) {
            if (request.resourceType == 'document') {
                console.log(o + `\nurl:${request.url}(${request.resourceType})\n` +
                    `method:${request.method}\n` +
                    `headers:\n${JSON.stringify(request.headers, null, '\t')}` + '\n' + o);
            }
        }
        request.continue();
    });
    page.on('response', async response => {
        if (start_record) {
            if (response.request().resourceType == 'document') {
                console.log(i + `\nurl:${response.url}\n` +
                    `status:${response.status}\n` +
                    `headers:\n${JSON.stringify(response.headers, null, '\t')}` + '\n' + i);
            }
        }
    });
})()
    .then(async () => {
        await page.goto(url);
        start_record = true;
        await page.evaluate((xpath) => {
            var node = document.evaluate(xpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
            node.click();
        }, xpath);
    })
```
The log:
`x3e6@x3e6:~/workspace/puppeteer$ node test.js`
`>>>>>>>>>>>>>>>>>>>>>>>>>>`
`url:http://218.60.147.62/xmglgs/ListView.aspx?pl=NPZP(document)`
`method:POST`
`headers:`
`{`
`	"origin": "http://218.60.147.62",`
`	"upgrade-insecure-requests": "1",`
`	"content-type": "application/x-www-form-urlencoded",`
`	"user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3264.0 Safari/537.36",`
`	"x-devtools-emulate-network-conditions-client-id": "(5924180339BA5D8EC77FA38CDAAD2E6E)",`
`	"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"`
`}`
`>>>>>>>>>>>>>>>>>>>>>>>>>>`
`<<<<<<<<<<<<<<<<<<<<<<<<<<`
`url:http://218.60.147.62/xmglgs/ListView.aspx?pl=NPZP`
`status:302`
`headers:`
`{`
`	"cache-control": "private",`
`	"content-type": "text/html; charset=utf-8",`
`	"location": "/xmglgs/Content.aspx?pl=NPZP&pid=d18af15219c24fecacabd739484b4369ff0edbc4d9cc4a619b05ec5fb8bdd0bf&CityCode=",`
`	"server": "Microsoft-IIS/7.5",`
`	"x-aspnet-version": "2.0.50727",`
`	"x-powered-by": "ASP.NET",`
`	"access-control-allow-origin": "*",`
`	"access-control-allow-credentials": "true",`
`	"date": "Wed, 10 Jan 2018 06:25:51 GMT",`
`	"content-length": "18781"`
`}`
`<<<<<<<<<<<<<<<<<<<<<<<<<<`
`>>>>>>>>>>>>>>>>>>>>>>>>>>`
`url:http://218.60.147.62/xmglgs/Content.aspx?pl=NPZP&pid=d18af15219c24fecacabd739484b4369ff0edbc4d9cc4a619b05ec5fb8bdd0bf&CityCode=(document)`
**`method:POST`**
`headers:`
`{`
`	"origin": "http://218.60.147.62",`
`	"upgrade-insecure-requests": "1",`
`	"content-type": "application/x-www-form-urlencoded",`
`	"user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3264.0 Safari/537.36",`
`	"x-devtools-emulate-network-conditions-client-id": "(5924180339BA5D8EC77FA38CDAAD2E6E)",`
`	"accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"`
`}`
`>>>>>>>>>>>>>>>>>>>>>>>>>>`
The bold line should be `method:GET` rather than `method:POST`, is it a bug?

**Comment by Glennvd** [comment]
FYI this has been fixed in the latest master chromium builds when using `--enable-features=NetworkService`, in case this is a blocking issue for anyone else.

**Comment by aslushnikov** [comment]
@Glennvd thanks for letting us know. FYI: Network Service is not fully ready yet and still doesn't pass all the pptr tests.

**Comment by Glennvd** [comment]
To add to that, it's not close to fully ready. At the moment `--enable-features=NetworkService` and the test mentioned here https://github.com/GoogleChrome/puppeteer/issues/1664#issuecomment-354090591 only work when running non-headless. Headless still fails.

**Comment by aslushnikov** [comment]
@Glennvd merging this to #3471. The first step there would be enabling NetworkService by default; it should address the problem here.

**Comment by kevinforrestconnors** [comment]
Enabling NetworkService is not a fix for me.  Using HeadlessChrome/75.0.3738.0, 302 redirect stays pending forever (in headless and non-headless modes)
