### ISSUE TITLE
page.goto never resolves when page.setRequestInterception is used (for some urls)

### ISSUE THREAD

**Issue by pocketjoso** [puppeteer/puppeteer#3118]
Hi again,
Thanks as usual for providing this library 👏. Unfortunately I am back with another `page.setRequestInterception` regression. :/ It's pretty much the same as https://github.com/GoogleChrome/puppeteer/issues/662, but since that was fixed back then I thought I'd open a new issue instead. I also saw [this new issue](https://github.com/GoogleChrome/puppeteer/issues/3085) which sounds like it's the same thing, but it's been closed and info removed, so cannot continue from.

What happens here is just simply that for some URLs, when `page.setRequestInterception` is used, `page.goto` never resolves. (And yes, I am calling `continue` on intercepted requests).

### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 1.7.0
1.6.2 did not have this issue
* Platform / OS version: MacOS 10.13.6 (17G65)
* URLs (if applicable): f.e. https://csms.org/tag/telehealth
This url I discovered this problem for, but it's a pattern I see applies for other urls as well (only some though). The url is not mine.
* Node.js version: v9.11.2

**What steps will reproduce the problem?**
Run the code below.

```js
const puppeteer = require('puppeteer');

(async() => {
const browser = await puppeteer.launch({
  ignoreHTTPSErrors: true
})
const page = await browser.newPage()

// With page.setRequestInterception(true)
// page.goto never resolves (below)
await page.setRequestInterception(true)
page.on('request', interceptedRequest => {
  interceptedRequest.continue()
})

console.log('goto start...')
await page.goto('https://csms.org/tag/telehealth')
console.log('this never happens')

browser.close();
})();
```

**What is the expected result?**
The page loads. Using `setRequestInterception` should not have any impact on whether a page loads or not, at least not if `continue` is called on every intercepted request.

**What happens instead?**
The page never loads.

**Comment by pocketjoso** [comment]
And I don't want to put extra pressure on you, but just sharing my side.
It's unfortunate that new releases break behaviors like this. I know the web is wide and wild, and it's hard to foresee every kind of crazy content that exists out there... but do you have test coverage for these kind of flows? Is it something you would want to have more of, and would accept help for?

I have to downgrade my puppeteer version again, until there's a fix for this. I'm hoping it won't be too hard :). Please let me know if you need any more info to help reproduce! I could provide a list of urls that timeout with puppeteer@1.7. I personally wonder if it could be related to SSL; I saw that the URL I provided here required `ignoreHTTPSErrors:true` to load, even if I remove the request interception.. (in 1.7 that is..)

**Comment by aslushnikov** [comment]
@pocketjoso First of all, I'm very sorry we regressed your scenario. The reason it doesn't work any more is because Chrome 70 [no longer trusts Symantec certificates](https://security.googleblog.com/2018/03/distrust-of-symantec-pki-immediate.html). As a result, you're hitting our long-standing bug #1159.

> It's unfortunate that new releases break behaviors like this. I know the web is wide and wild, and it's hard to foresee every kind of crazy content that exists out there... but do you have test coverage for these kind of flows?

As you said, web is wide and wild, and we're running Puppeteer with the tests-first mantra. Every time we break something we add a regression test so that it doesn't happen in future; over time, the project will become more and more reliable. 

Regarding the #1159 - Chromium is slowly completing migration to network service, so once it's their, I'll be the first to open champagne. For now, you can workaround this by enabling network service manually. 

The following works for me:

```js
const puppeteer = require('puppeteer');

(async() => {
  const browser = await puppeteer.launch({
    args: ['--enable-features=NetworkService'],
    ignoreHTTPSErrors: true
  })
  const page = await browser.newPage()
  await page.setRequestInterception(true)
  page.on('request', interceptedRequest => {
    interceptedRequest.continue()
  })
  console.log('goto start...')
  await page.goto('https://csms.org/tag/telehealth')
  console.log('this never happens')
  browser.close();
})();
```

Thank you for your reports. Closing as dupe of #1159.

**Comment by pocketjoso** [comment]
Thanks for this answer @aslushnikov, it seems to improve things even in 1.6.2 where I also started seeing some similar problems. Will test more, then upgrade to 1.7 and test more again. :)

Do you have any link for more information about the NetworkService work in Chrome? I have not heard of this before.

**Comment by aslushnikov** [comment]
> Do you have any link for more information about the NetworkService work in Chrome?

@pocketjoso network service is a part of a "servicification effort", you can read more about it [here](https://www.chromium.org/servicification).

**Comment by pocketjoso** [comment]
@aslushnikov I just saw the release of 1.8 and in particular:
> request interception now works with ignorehttpserrors option

Does this mean that we no longer need your workaround, i.e
`    args: ['--enable-features=NetworkService']`

I will do some tests on my own, but perhaps you know without a question whether this is the case or not.

**Comment by aslushnikov** [comment]
@pocketjoso yes, the #1159 is now fixed for non-network-service codepath.

**Comment by jlcd** [comment]
@aslushnikov still not working here... 
anything specific I should do?

```js
    const browser = await puppeteer.launch({
        headless: false,
        ignoreHTTPSErrors: true,
        args:[
            '--window-size=1280,768',
            '--no-sandbox',
        ] 
    });
    const page = await browser.newPage();
    page.setViewport({width:1280, height:768});

    await page.setRequestInterception(true);
    page.on('request', async interceptedRequest => {

    ...
```

**Comment by aslushnikov** [comment]
@jlcd please file a separate bug with a full code snippet - one that we can run locally to debug your issue. Thanks!

**Comment by jlcd** [comment]
From what I saw my issue will be fixed with #3471, so I'll keep an eye on that one. Thanks.

**Comment by skwidy** [comment]
Any updates ?

**Comment by aslushnikov** [comment]
@skwidy this issue is fixed; there's no good ETA for #3471.

**Comment by skwidy** [comment]
By fixed, you mean we need to downgrade to 1.6.2 ?

**Comment by aslushnikov** [comment]
@skwidy please see https://github.com/GoogleChrome/puppeteer/issues/3118#issuecomment-417754246 and subsequently https://github.com/GoogleChrome/puppeteer/issues/1159

**Comment by mullojo** [comment]
In case someone is reading this older issue, I'm just including the key details that worked for me after a lot of trials.  There is no bug or issue anymore, but in many examples I've seen code that is not ideal on this topic.

It is important to use async/await and `await request.continue()` for intercepting `requests` (outgoing) and then async/await for any `responses` (incoming) too.

```js
    
    const browser = await puppeteer.launch({
        //ignoreHTTPSErrors: true,  (not required)
        //args: ['--enable-features=NetworkService'],  (not required)
        headless: false,
        devtools: true,
        slowMo: 10 // slow down by 10ms
    });

    const page = await browser.newPage();

    await page.setRequestInterception(true);

    page.on('request', async request => {
        console.log('INTERCEPTED Request: ' + request.url());
        console.log(await request.method());
        try {
            await request.continue(); 
        } catch (err) {
            console.log(err);
        }
    });

    page.on('response', async response => {
        console.log('INTERCEPTED Response: ' + response.url());
        console.log(await response.status());
        
    });
```

**Comment by chaseholland** [comment]
For anyone else tracking requests for a short period of time (not the whole run) -- it's important to turn `setRequestInterception` back off when you're done, else all you're requests will hang for no apparent reason. 

This not a bug, but a point of confusion.

Here's an example of what to do:
```javascript
const promises = [];
const onRequest = (request) => promises.push(request.continue());
await page.setRequestInterception(true);
page.on('request', onRequest);
// .....
await Promise.all(promises);
page.removeListener('request', onRequest);
await page.setRequestInterception(false);
```

**Comment by vdkkia** [comment]
Make sure `req.continue()` is running in the interceptor.

**Comment by TheGP** [comment]
So in some many years they didnt fix it?
