### ISSUE TITLE
Version 1.9.0 not running on Google Cloud Function

### ISSUE THREAD

**Issue by shashank-** [puppeteer/puppeteer#3424]
Attempting to use version 1.9.0 of puppeteer on Google Cloud Function is returning the following error.

> 
**Error: Failed to launch chrome! /srv/node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md at onClose (/srv/node_modules/puppeteer/lib/Launcher.js:339:14
 at Interface.helper.addEventListener (/srv/node_modules/puppeteer/lib/Launcher.js:328:50
 at emitNone (events.js:111:20
 at Interface.emit (events.js:208:7
 at Interface.close (readline.js:370:8
 at Socket.onend (readline.js:149:10
 at emitNone (events.js:111:20
 at Socket.emit (events.js:208:7
 at endReadableNT (_stream_readable.js:1064:12
 at _combinedTickCallback (internal/process/next_tick.js:138:11)**

I have reverted back to 1.7.0 currently and that is still working.

**Comment by shashank-** [comment]
I have tried this with version 1.8.0 as well on GCF (Node 8) still failing.

**Comment by liron-navon** [comment]
It worked for me yesterday, and now it's broken for me too, maybe some issue with firebase?

```
Error: Failed to launch chrome!
/srv/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/srv/node_modules/puppeteer/lib/Launcher.js:299:14)
    at Interface.helper.addEventListener (/srv/node_modules/puppeteer/lib/Launcher.js:288:50)
    at emitNone (events.js:111:20)
    at Interface.emit (events.js:208:7)
    at Interface.close (readline.js:370:8)
    at Socket.onend (readline.js:149:10)
    at emitNone (events.js:111:20)
    at Socket.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

**Comment by genlu2011** [comment]
Tries today. Still broken for me. 
Error: Failed to launch chrome! /srv/node_modules/puppeteer/.local-chromium/linux-594312/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md at onClose (/srv/node_modules/puppeteer/lib/Launcher.js:339:14) at Interface.helper.addEventListener (/srv/node_modules/puppeteer/lib/Launcher.js:328:50) at emitNone (events.js:111:20) at Interface.emit (events.js:208:7) at Interface.close (readline.js:370:8) at Socket.onend (readline.js:149:10) at emitNone (events.js:111:20) at Socket.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:138:11)

**Comment by aslushnikov** [comment]
Dupe of #3422 - should be fixed right now.

**Comment by shauntrennery** [comment]
@aslushnikov I'm still seeing this with 1.10.0 deployed to a Firebase Function

`TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r599821
    at Timeout.onTimeout (/srv/node_modules/puppeteer/lib/Launcher.js:353:14)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)`

**Comment by DavidBater** [comment]
Exactly the same error message for me, version 1.10 in Node 8 Cloud Functions.
Hangs on this line of code:
`const browser = await puppeteer.launch({args: ['--no-sandbox']});`

**Comment by davidbater** [comment]
> @aslushnikov I'm still seeing this with 1.10.0 deployed to a Firebase Function
> 
> `TimeoutError: Timed out after 30000 ms while trying to connect to Chrome! The only Chrome revision guaranteed to work is r599821 at Timeout.onTimeout (/srv/node_modules/puppeteer/lib/Launcher.js:353:14) at ontimeout (timers.js:482:11) at tryOnTimeout (timers.js:317:5) at Timer.listOnTimeout (timers.js:277:5)`

Had this same issue and after half a day I realised I was a complete dimwit and tried to do async stuff in a function called by an otherwise non-async HTTP function. Some wiser people will correct me if i'm wrong but I believe the instance running your function terminates in this case, thus leaving your puppeteer.launch() hanging. At least that was the issue for me, might be something else for you.
https://firebase.google.com/docs/functions/terminate-functions

**Comment by shauntrennery** [comment]
@DavidBater I'm using Firebase's PubSub trigger so I don't think that is the case.

**Comment by brandondurham** [comment]
Oddly enough, this is happening for me on my work desktop but not on my home desktop. Both environments are identical.
