### ISSUE TITLE
Closing IncognitoBrowserContext with devtools: true also closes the main context

### ISSUE THREAD

**Issue by matheusb-comp** [puppeteer/puppeteer#4207]
### Steps to reproduce

**Environment:**

* Puppeteer version: 1.13.0
* Platform / OS version: Linux Mint 19 (Ubuntu 18.04 LTS)
* Node.js version: 10.15.3

**What steps will reproduce the problem?**

I have a function that creates an incognito browser context, then creates a page, and returns this page. I want the context to be closed whenever the page is closed, and for that I use the context's `targetdestroyed` event. (example script below)

All of it works, unless I launch puppeteer with the `devtools: true` option. In this case, the main browser is also closed.

```
const puppeteer = require('puppeteer')

const getPage = async (browser) => {
  const google = 'https://www.google.com/'
  const ctx = await browser.createIncognitoBrowserContext()
  const page = await ctx.newPage()
  await page.goto(google)

  // Destroy the incognito context when the page's target is destroyed
  ctx.on('targetdestroyed', async (t) => {
    if (t.url() === google) {
      try {
        await ctx.close()
        console.log('Incognito context closed!')
      } catch (e) {
        console.error('Closing context failed:', e)
      }
    }
  })

  return page
}

const run = async () => {
  const browser = await puppeteer.launch({ headless: false, devtools: true })

  const pages = await Promise.all([1, 2, 3, 4, 5].map(() => getPage(browser)))
  console.log('Number of contexts:', browser.browserContexts().length) // 6

  // Close all pages, only the default context (not incognito) should remain open
  await Promise.all(pages.map((p) => p.close()))

  // Wait 1 second before printing the number of contexts
  await (new Promise((resolve) => setTimeout(() => resolve(), 1000)))

  console.log('Number of contexts:', browser.browserContexts().length) // 1
}

run().then(() => console.log('success')).catch((e) => console.error('fail:', e))
```

**What is the expected result?**

This is the actual result when Puppeteer is launched with `devtools: false`
```
$ node test.js
Number of contexts: 6
Incognito context closed!
Incognito context closed!
Incognito context closed!
Incognito context closed!
Incognito context closed!
Number of contexts: 1
success
```

**What happens instead?**

The main browser window is closed, but the exact moment varies, here are two different output I got in this same script with `devtools: true`

```
$ node test.js
Number of contexts: 6
Incognito context closed!
$
```

```
$ node test.js
Number of contexts: 6
Incognito context closed!
Incognito context closed!
Incognito context closed!
Incognito context closed!
$
```

**Comment by matheusb-comp** [comment]
Also tried closing the context with the new [`page.browserContext()`](https://pptr.dev/#?product=Puppeteer&version=v1.13.0&show=api-pagebrowsercontext) instead of the event callback, but the same thing happens if `devtools: true`

**Comment by matheusb-comp** [comment]
Issue still happening in version 1.17.0

<details>
<summary>Errors</summary>
<p>

```
{ Error: Protocol error (Target.disposeBrowserContext): Target closed.
    at Promise (/home/user/Documents/puppeteer/node_modules/puppeteer/lib/Connection.js:74:56)
    at new Promise (<anonymous>)
    at Connection.send (/home/user/Documents/puppeteer/node_modules/puppeteer/lib/Connection.js:73:12)
    at Browser._disposeContext (/home/user/Documents/puppeteer/node_modules/puppeteer/lib/Browser.js:104:28)
    at BrowserContext.close (/home/user/Documents/puppeteer/node_modules/puppeteer/lib/Browser.js:379:25)
    at BrowserContext.<anonymous> (/home/user/Documents/puppeteer/node_modules/puppeteer/lib/helper.js:111:23)
    at run (/home/user/Documents/puppeteer/index.js:40:30)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  message:
   'Protocol error (Target.disposeBrowserContext): Target closed.' }
Error: WebSocket is not open: readyState 3 (CLOSED)
    at WebSocket.send (/home/user/Documents/puppeteer/node_modules/ws/lib/websocket.js:329:19)
    at WebSocketTransport.send (/home/user/Documents/puppeteer/node_modules/puppeteer/lib/WebSocketTransport.js:57:14)
    at Connection._rawSend (/home/user/Documents/puppeteer/node_modules/puppeteer/lib/Connection.js:86:21)
    at Connection.send (/home/user/Documents/puppeteer/node_modules/puppeteer/lib/Connection.js:72:21)
    at Browser._disposeContext (/home/user/Documents/puppeteer/node_modules/puppeteer/lib/Browser.js:104:28)
    at BrowserContext.close (/home/user/Documents/puppeteer/node_modules/puppeteer/lib/Browser.js:379:25)
    at BrowserContext.<anonymous> (/home/user/Documents/puppeteer/node_modules/puppeteer/lib/helper.js:111:23)
    at run (/home/user/Documents/puppeteer/index.js:40:30)

```

</p>
</details>

**Comment by aslushnikov** [comment]
@matheusb-comp Interestingly, your script works fine for me with the upcoming [chromium roll to r665405](https://github.com/aslushnikov/puppeteer/tree/roll-r665405). 

It might be that the problem is fixed upstream already.

<details>
<summary>script I tried</summary>
<p>

```js
const puppeteer = require('puppeteer')

async function getPage(browser) {
  const ctx = await browser.createIncognitoBrowserContext()
  const page = await ctx.newPage()
  await page.goto('https://www.google.com/')

  // Destroy the incognito context when the page's target is destroyed
  ctx.on('targetdestroyed', async (t) => {
    if (t.url() === 'https://www.google.com/') {
      try {
        await ctx.close()
        console.log('Incognito context closed!')
      } catch (e) {
        console.error('Closing context failed:', e)
      }
    }
  })
  return page;
}

const run = async () => {
  const browser = await puppeteer.launch({ headless: false, devtools: true })

  const pages = await Promise.all([1, 2, 3, 4, 5].map(() => getPage(browser)))
  console.log('Number of contexts:', browser.browserContexts().length) // 6

  // Close all pages, only the default context (not incognito) should remain open
  await Promise.all(pages.map((p) => p.close()))

  // Wait 1 second before printing the number of contexts
  await (new Promise((resolve) => setTimeout(() => resolve(), 1000)))

  console.log('Number of contexts:', browser.browserContexts().length) // 1
}

run().then(() => console.log('success')).catch((e) => console.error('fail:', e))
```

</p>
</details>

<details>
<summary>output I get</summary>
<p>

```
lushnikov:~/prog/puppeteer(roll-r665405)$ node a.mjs
Number of contexts: 6
Incognito context closed!
Incognito context closed!
Incognito context closed!
Incognito context closed!
Incognito context closed!
Number of contexts: 1
success
```

</p>
</details>

**Comment by underflow00** [comment]
This is not fixed. I can reproduce sometimes, without `devtools = true`. Adding a 100ms delay before `ctx.close()` fixes it. Race condition?
