### ISSUE TITLE
Browser caching doesn't seem to work

### ISSUE THREAD

**Issue by aslushnikov** [puppeteer/puppeteer#487]
The following example reloads the `example.com` a few times.
For some reason, all the responses have status 200. If there was a caching, the responses would have status 304. 

```js
const puppeteer = require('.');

(async () => {
  const browser = await puppeteer.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://example.com/');

  page.on('response', r => console.log(r.status + ' ' + r.url));
  await page.reload();
  await page.reload();
  await page.reload();
  browser.close();
})();
```

This was initially reported in #446.

**Comment by pavelfeldman** [comment]
Ouch, you are likely getting into the wrong branch of [this](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/inspector/InspectorNetworkAgent.cpp?sq=package:chromium&l=389). The way it works is that browser receives 304, but instead of passing it into Blink, it is fetching data from disk cache and feeds Blink with the 200 response. Clueless renderer behaves as it is getting an OK response.

Not getting into that branch means that we don't have raw headers, don't report precise network timing, etc. I.e. needs to be fixed on the headless side. If you see this on Linux/Window headless and don't see it on a Mac, we are not plumbing the raw headers information the right way. Should be a straightforward fix in `headless`.

**Comment by aslushnikov** [comment]
@pavelfeldman doesn't seem to be related to headless: it reproduces for me on mac headful and on mac headless.

**Comment by aslushnikov** [comment]
Pavel bisected it down to chromium change.
Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=758090

**Comment by aslushnikov** [comment]
For the record: this was fixed upstream in r498894.

**Comment by pokka** [comment]
Still not getting the cache, all resources(png, css) got 200, but I'm using headless mode.
Can anyone help?

Tested in v1.0.0-rc:
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage({ context: 'default' });
  await page.goto('https://github.com/GoogleChrome/puppeteer/issues/487');

  page.on('response', r => console.info(r.status() + ' ' + r.url()));
  await page.reload();
  await page.reload();
  await page.reload();
  browser.close();
})();
```

**Comment by aslushnikov** [comment]
@pokka the same happens to me if I just open the website in chrome and try to reload: all resources are loaded with 200 (check out devtools network panel). Looks like server disabled caching.

**Comment by robba86** [comment]
Any update on this? :)

**Comment by aslushnikov** [comment]
@robba86 this has been fixed; if it doesn't work for you - please file another issue.

**Comment by ColCh** [comment]
@pokka it's working for me

set `DEBUG` env variable to `'puppeteer:*'` and log things

then search for `fromDiskCache`. There is many requests with cache

**Comment by liuchuangjun321** [comment]
> things

Can explain the details, thank you

**Comment by liuchuangjun321** [comment]
> @pokka it's working for me
> 
> set `DEBUG` env variable to `'puppeteer:*'` and log things
> 
> then search for `fromDiskCache`. There is many requests with cache

@ColCh Can explain the details, thank you。
I am still not getting the cache, all resources(png, css) got 200,
