### ISSUE TITLE
using --user-data-dir=profilepath corrupts settings and remove all extensions

### ISSUE THREAD

**Issue by BenHayak** [puppeteer/puppeteer#527]
Launching with args:
```js
	const browser = await puppeteer.launch({
	  headless: false,
	  args: ['--user-data-dir=/pathtoprofile/'],
	});
```
Will override some files and removes all extensions from the chrome profile + alerts for "settings corrupted" at chrome://settings screen.

**Comment by aslushnikov** [comment]
Might be related to #411, and might be related to some headless specifics

**Comment by aslushnikov** [comment]
This should be fixed on tip-of-tree.

**Comment by aslushnikov** [comment]
Ah no, requires more testing.

**Comment by kaytwo** [comment]
I'm still seeing this exact behavior in version 0.13.0 on OSX.

**Comment by aslushnikov** [comment]
@kaytwo can you please file another issue with a step-by-step scenario? It will help us reproduce your issue locally.

**Comment by kaytwo** [comment]
#1404
