### ISSUE TITLE
Puppeteer not working in Google Cloud Function, missing libgbm

### ISSUE THREAD

**Issue by rhgraham** [puppeteer/puppeteer#5674]
### Steps to reproduce

Obviously this is more a problem with whatever image GCP is using for its Function environment, but troubleshooting.md does claim that Function and App Engine Standard support puppeteer out of the box. If nothing else, the docs should be updated.

**Tell us about your environment:**

* Puppeteer version: 3.0.0
* Platform / OS version: Ubuntu 18.04
* URLs (if applicable):
* Node.js version: 10.18.1

**What steps will reproduce the problem?**
Attempt to use puppeteer 3.0.0 in Google Cloud Function Nodejs10 execution environment.

**What is the expected result?**
No error. As per troubleshooting.md, GCP Function and App Engine have all necessary dependencies for puppeteer.

**What happens instead?**
/workspace/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory

**Comment by fcollonval** [comment]
This error happens also using GitHub workflows with the [Ubuntu 18.04.4 LTS](https://github.com/actions/virtual-environments/blob/ubuntu18/20200406.2/images/linux/Ubuntu1804-README.md) image.

The falling job: https://github.com/jupyterlab/extension-cookiecutter-ts/runs/593913260

```
info Direct dependencies
└─ puppeteer@3.0.0
```

```
Error: Failed to launch the browser process!
/opt/hostedtoolcache/Python/3.7.6/x64/share/jupyter/lab/browser_test/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: 
error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
```

The latest CI job working was based on [Ubuntu 18.04 image](https://github.com/actions/virtual-environments/blob/ubuntu18/20200330.1/images/linux/Ubuntu1804-README.md). This was using puppeteer@2.1.1.

In both working and failing case, the Node.js version is 10.20.1.

**Comment by branciard** [comment]
Having also this issue on docker image from debian:stable (Buster). 
Installing :
```
apt-get -y install libgbm1
```
fix this error for me.

**Comment by ScreenDev** [comment]
I have the same exact issue. (using 3.0.0 on Google Cloud Functions) First time puppeteer user here and for two days I've been trying to figure out what I'm doing wrong (getting same exact error message). I also tried installing 2.1.1 instead, but still getting the same error message. I am unable to install libbgm from cloud shell? (with above command) Is there any way to fix this/workaround?

**Comment by tamarasaurus** [comment]
I have the exact same issue, I ended up downgrading back to `v1.14.0` to get it working

**Comment by ScreenDev** [comment]
> I have the exact same issue, I ended up downgrading back to `v1.14.0` to get it working

I can confirm this works for me, too. This is the first time I got puppeteer working with one of my Google Cloud Functions and it's nice to know that  I'm not crazy. At least I can do *something* now. Haha. Thank you!

**Comment by cirdes** [comment]
I still can't run puppeteer 3.0.1 in Google Cloud Function. There is any workaround?

**Comment by owenkealey** [comment]
Also having this problem w/ puppeteer 3.0.1 but in the standard google app engine environment.

**Comment by Whoweez** [comment]
Running nodejs 10 and GAE standard with puppeteer 3.0.2 and getting the same error... Any fox yet?

**Comment by owenkealey** [comment]
I fixed it by downgrading puppeteer to 2.1

**Comment by shinhyo** [comment]
~~fixed in v3.0.4 😍~~

https://github.com/puppeteer/puppeteer/releases/tag/v3.0.4

**Comment by 1hakr** [comment]
@mathiasbynens  @jackfranklin still not working even with v3.0.4
Error:
`/workspace/node_modules/puppeteer/.local-chromium/linux-737027/chrome-linux/chrome: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory`

I tested on 
Puppeteer version: 3.0.4
Platform / OS version: Ubuntu 20.04
Node.js version: 10.20.0

**Comment by hudus** [comment]
> fixed in v3.0.4 😍
> 
> https://github.com/puppeteer/puppeteer/releases/tag/v3.0.4

Still not working for me on Firebase Functions with Puppeteer 3.0.4 and node v10 :(

**Comment by SinanGabel** [comment]
I could not get it to work with 3.* and google cloud functions either,
it works with 2.1.1 and google cloud functions with nodejs 10.x. and 2 GB
memory.

**Comment by nikhilag** [comment]
3.0.4 is not working for me either in cloud function. Why is this issue closed? Has it been fixed for some upcoming release?

**Comment by annez** [comment]
This is still an issue with 3.0.4 and Google Cloud Functions @mathiasbynens could we re-open this issue?

**Comment by ManuelWandeto** [comment]
puppeteer 3.1.0 is not working for me with Firebase Functions on node 10, downgrading to 2.1.1

**Comment by ManuelWandeto** [comment]
puppeteer 2.1.1 works fine with Firebase functions on node 10 engine

**Comment by starrify** [comment]
I'm unsure whether the maintainers would reopen this issue, as there's already #5704 which is for exactly the same case (weird that none has yet linked these two).

Please refer to #5704 for further updates. TL;DR:
- Google Cloud may soon update the system environment and have the necessary dependencies included: https://github.com/puppeteer/puppeteer/issues/5704#issuecomment-626873725
- There's a temporary workaround: https://github.com/puppeteer/puppeteer/issues/5704#issuecomment-632969782

**Comment by jasonc624** [comment]
Not working for Firebase Functions with Puppeteer 3.3.0 and node 10 engine

**Comment by textarea** [comment]
Not working also for Firebase Functions with Puppeteer 5.0.0 and node 10 engine

**Comment by okydk** [comment]
Seems to be fixed in the new node 12 (beta) engine. 🎉

**Comment by Siddharthosatwal** [comment]
> Seems to be fixed in the new node 12 (beta) engine. 🎉

No, it's not working with Node v12 on Cloud Run. Encountered the same issue.

**Comment by yan-michael** [comment]
Is this issue still happening for others?

**Comment by Siddharthosatwal** [comment]
> Is this issue still happening for others?

Yes.

**Comment by yan-michael** [comment]
> > Is this issue still happening for others?
> 
> Yes.

Any workarounds? Trying to set up a webscraper on cloud functions

**Comment by ghost** [comment]
> > > Is this issue still happening for others?
> > 
> > 
> > Yes.
> 
> Any workarounds? Trying to set up a webscraper on cloud functions

Use puppeteer version 2.1.0
That's the most recent version that I've gotten working on cloud functions.

**Comment by KillDozerX2** [comment]
> > > > Is this issue still happening for others?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > Any workarounds? Trying to set up a webscraper on cloud functions
> 
> Use puppeteer version 2.1.0
> That's the most recent version that I've gotten working on cloud functions.

I literally just tried with puppeteer 2.1.0 and Node v10, and it isn't working.

**Comment by ghost** [comment]
> > > > > Is this issue still happening for others?
> > > > 
> > > > 
> > > > Yes.
> > > 
> > > 
> > > Any workarounds? Trying to set up a webscraper on cloud functions
> > 
> > 
> > Use puppeteer version 2.1.0
> > That's the most recent version that I've gotten working on cloud functions.
> 
> I literally just tried with puppeteer 2.1.0 and Node v10, and it isn't working.

Truthfully I didn't try with node 10, I did it with node 12 and that worked. If you're able to try with node12 I'd do that. Otherwise you might have to try with an even older version of puppeteer. Also, you could just have another problem with your code. What's the error you're getting?

**Comment by heinnge** [comment]
"puppeteer": "5.3.1" is working okay with `nodejs12` in google cloud functions. New version that came out recently than this are not working in `nodejs12` cloud functions.

**Comment by jorgemndoza** [comment]
@heinnge thank you so much. You saved me lol. Days trying to find a solution.

**Comment by frankie567** [comment]
I can confirm that it works with the new `nodejs14` runtime and puppeteer `v5.5.0`, following @heinnge suggestions. It seems that there are incompatibilities with newer versions of puppeteer.

**Comment by marcosmrs8** [comment]
Works for me using puppeteer `v12.0.0` and `nodejs14`

**Comment by SinanGabel** [comment]
> I can confirm that it works with the new `nodejs14` runtime and puppeteer `v5.5.0`, following @heinnge suggestions. It seems that there are incompatibilities with newer versions of puppeteer.

I have a working combination of nodejs 16 and puppeteer 5.5.0 - without any extra libraries i.e. just use cloud functions as-is. 
With puppeteer 14.x there are timeout problems, so I rolled back to 5.5.0.

**Comment by stevejboyer** [comment]
> Works for me using puppeteer `v12.0.0` and `nodejs14`

Confirming this works for me. Thank you! I've been beating my head against the keyboard for a few days now.
