### ISSUE TITLE
[7.0.1] LaunchOptions and Page types are not exported from main

### ISSUE THREAD

**Issue by AviVahl** [puppeteer/puppeteer#6816]
### Steps to reproduce

**Tell us about your environment:**

* Puppeteer version: 7.0.1
* Platform / OS version: Fedora 33
* Node.js version: 14.15.4

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

```ts
import puppeteer from 'puppeteer';
(async () => {
  const launchOptions: puppeteer.LaunchOptions = { devtools: true };
  const browser = await puppeteer.launch(puppeteerConfig);
...
})();
```

**What is the expected result?**

Interfaces are available on the namespace.
Work the same way it did with @types/puppeteer.

**What happens instead?**

They are not exposed. I'm sure there are many more. Will write any I notice here.

**Comment by AviVahl** [comment]
For:
`page.on('dialog', (dialog) => dialog.dismiss());`

 dialog doesn't get inferred anymore.

**Comment by mathiasbynens** [comment]
cc @jackfranklin

**Comment by wavded** [comment]
also `Browser` isn't either

**Comment by thomassuckow** [comment]
and CDPSession. I don't think any of the types are actually being exported.

**Comment by thomassuckow** [comment]
So yes, no types are exported. Just the default is export. What should be happening is
```ts
export * from "common/Browser"
export * from "common/Connection"
export * from "common/DeviceDescriptors"
export * from "common/Page"
...
```

This ideally would happen in the node*.ts files and then the cjs shim at the root could `export *` instead of just the default as well.

Somehow the default export should also be a namespace...

**Comment by thomassuckow** [comment]
Also instead of re-exporting everything again, api-docs-entry already has all the things with types. So in `cjs-entry*.d.ts` you can also do:

```
export * from "./lib/cjs/puppeteer/api-docs-entry";
```

Still doesn't solve being able to do like `import {devices} from "puppeteer-core";`. That may be solvable by changing the export in `src/node*.ts` to `export = initializePuppeteerNode[...]`. Then the `cjs-entry*.d.ts` would be changed to export * from it as well. I haven't tested this though and I've never personally used the `export =` syntax.

**Comment by berstend** [comment]
As a maintainer of a plugin framework for puppeteer this is quite a painful situation for me 😅 

Does anyone know a trick to make TS ignore the built-in types and use `@types/puppeteer` instead? The latter being a little outdated, but at least they work 😄 

edit, a hacky workaround: Install `@types/puppeteer-core` and use:
```js
import type * as Puppeteer from 'puppeteer-core'
```

This will probably not work when consumers install `puppeteer-core` though.

**Comment by berstend** [comment]
Nuclear option:
- Create a `src/types/puppeteer.ts` file in your project
- Add `declare module 'puppeteer' { }`
- Copy paste the contents of [this file](https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/puppeteer/index.d.ts) between the curly brackets
- String replace `declare ` with `export `
- Use `import type * as Puppeteer from 'puppeteer'`

:smiling_face_with_tear:

**Comment by k-yle** [comment]
even in v7.0.1 the type definitions don't work at all if you use `require()` instead of `import`. I've opened #6827 to fix that by using the `export =` syntax. 

cc @jackfranklin, I saw your comment on a7e3c2e09e9163eee2f15221aafa4400e6a75f91

**Comment by thomassuckow** [comment]
Should be resolved by #6837 once it is merged/released

**Comment by AviVahl** [comment]
Fixed in v7.0.4. Thanks.

**Comment by mceachen** [comment]
In case anyone else was using `"@types/puppeteer` and now using the built-in types, but wondering why your compile is still broken (even with v7.0.4): know that several type names have changed, like `Request` is now `HTTPRequest`, and `Response` is now `HTTPResponse`.
