### ISSUE TITLE
userDataDir + headless = lost authorization

### ISSUE THREAD

**Issue by vsemozhetbyt** [puppeteer/puppeteer#921]
* Puppeteer version: v0.12.0-alpha
* Platform / OS version: Windows 7 x64
* URLs (if applicable): any that needs authorization

1. Create a test script and an empty folder `test-profile-dir`:
```js
'use strict';

const puppeteer = require('puppeteer');

(async function main() {
  try {
    const browser = await puppeteer.launch({
      headless: false,
      userDataDir: 'test-profile-dir',
    });
    const page = await browser.newPage();

    await page.goto('https://twitter.com/');

    console.log(await page.evaluate(() => document.title));
    console.log(await page.evaluate(() => document.cookie));

    // await browser.close();
  } catch (err) {
    console.error(err);
  }
})();
```
You will see something like this:
```console
Twitter. It's what's happening.

personalization_id=...; guest_id=...; ct0=...
```
Sign in into Twitter and close the browser.

2. Run the same script second time (`await browser.close();` can be uncommented). You will see something like this:
```console
Twitter

personalization_id=...; guest_id=...; ct0=...; ads_prefs=...; remember_checked_on=...;
twid=...; tip_nightmode=...; _ga=...; _gid=...; dnt=...; lang=...
```
3. Run the same script, but with `headless: true,` The output is the same as before authorization:
```console
Twitter. It's what's happening.

personalization_id=...; guest_id=...; ct0=...
```

I have tried various sites, all of them seem to lose authorization in headless mode.

Some more notes:

* `response.request().headers` does not contain cookies in both `headless: false` and `headless: true` modes.

* `console.log(await page.cookies('https://twitter.com/'));` contains many cookies in the `headless: false` mode. In the `headless: true` mode it gives an empty array `[]`.

**Comment by chuckchamberland** [comment]
I can duplicate this on MacOS 10.10.5 using 0.11.0 and facebook.

I'm also having trouble with an internal site I'm trying to automate, but also seeing it in headful mode. I only mention it here because of the note about 'response.request().headers' not containing cookies.

**Comment by klaus82** [comment]
Hello,
made some test.
In the both cases of the test added (page and page2),  into the function launch of Launcher.js the userDataDir are correct,  the folder logged is the same.

**Comment by aslushnikov** [comment]
For the record: upstream bug is filed as https://crbug.com/771830

**Comment by vsemozhetbyt** [comment]
@aslushnikov Is it connected? In OP's case, two first runs are with `headless: false` — so the issue is not in closing with `headless: true`, it is in not sending cookies with `headless: true` that have been successfully saved by previous runs.

Did you mean https://github.com/GoogleChrome/puppeteer/issues/918 ?

**Comment by fhmd4k** [comment]
The chromium can't save and restore storage and cookies in headless mode. It's chromium bug.

**Comment by fhmd4k** [comment]
It's chromium bug. It's not puppeteer bug.
On windows, you can run fiddler capture url cookies and then run chrome:(test some have cookie site)
`chrome --user-data-dir=C:\Users\xxx\Desktop\testud --headless -- "https://www.example.com"`

run some times, you can find the cookie is different in every times(same userDataDir)

**Comment by aslushnikov** [comment]
This is actually **not fixed** by #1028.

**Comment by vsemozhetbyt** [comment]
Refs: https://github.com/GoogleChrome/puppeteer/pull/1055#issuecomment-337326682

**Comment by JoelEinbinder** [comment]
This should be fixed as of #1063. @vsemozhetbyt can you confirm? Thanks

**Comment by vsemozhetbyt** [comment]
@JoelEinbinder Unfortunately, exactly this case from OP still is not fixed: logging in in headful mode is not restored in headless mode. I did not test if cookies are stored and restored in completely headless mode — this can be fixed, but for me, this is rather a speculative use case.

**Comment by aslushnikov** [comment]
For the record: this is tracked by upstream bug https://bugs.chromium.org/p/chromium/issues/detail?id=775703

**Comment by vsemozhetbyt** [comment]
[Seems to be fixed upstream.](https://bugs.chromium.org/p/chromium/issues/detail?id=775703#c7)

**Comment by vsemozhetbyt** [comment]
@aslushnikov @JoelEinbinder Unfortunately, https://github.com/GoogleChrome/puppeteer/pull/1259 does not fix the case in the OP: the outputs of the examples still differ and the `console.log(await page.cookies('https://twitter.com/'));` still displays many cookies in the `headless: false` mode and much fewer cookies in the the `headless: true` mode.

**Comment by vsemozhetbyt** [comment]
Strange. Why cannot I reopen the issue?

**Comment by aslushnikov** [comment]
@vsemozhetbyt we're very sorry; it indeed doesn't work! We're on it.

**Comment by aslushnikov** [comment]
For the record: upstream patch is up for review https://chromium-review.googlesource.com/c/chromium/src/+/752743

**Comment by vsemozhetbyt** [comment]
@aslushnikov Sorry, https://github.com/GoogleChrome/puppeteer/commit/2f7c77875ec56f20b7064704d91f002115a4efef still does not fix the case in the OP, the status quo from the https://github.com/GoogleChrome/puppeteer/issues/921#issuecomment-341574397 remains.

**Comment by aslushnikov** [comment]
@vsemozhetbyt just checked, it worked for me on Mac OS X. I'll check on Windows shortly. Meanwhile, are you sure you ran the 'npm install' so that pptr downloaded a new chromium binary?

**Comment by vsemozhetbyt** [comment]
@aslushnikov Yes, I've run `npm install https://github.com/GoogleChrome/puppeteer` and checked the version in the `.local-chromium` (is `64.0.3262.0` / `514418`).

**Comment by JoelEinbinder** [comment]
I can reproduce this on windows, although the test `headless should be able to read cookies written by headful` passes for me.

**Comment by vsemozhetbyt** [comment]
Is there any progress plan for this issue? Still not working with the last tip of the tree.

**Comment by aslushnikov** [comment]
@vsemozhetbyt we'll have it fixed, but there's no good ETA. Headless team is aware about it

**Comment by vsemozhetbyt** [comment]
@aslushnikov Thank you!

**Comment by sarfraznawaz2005** [comment]
I am also having the same issue on Windows 8. In headless mode, session/cookie info is lost. 

I am using puppeteer 0.13.0, node 8.9.1 and chrome that bundles with puppeteer is 64.0.3264.0 (Developer Build) (64-bit).

**Comment by sarfraznawaz2005** [comment]
Seems like this one will never close :smile:

**Comment by jimthedev** [comment]
@aslushnikov Thanks for keeping on this one. Is there a chrome bug I can track?

**Comment by bondansebastian** [comment]
Hello, is there any updates for this issue ?

I'm also experiencing this problem using `puppeteer ^1.6.1`, bundled `chromium 69.0.3494.0`, and `Windows 10` OS

**Comment by GHXST01** [comment]
Also having this issue! Launching a new driver in headless with the same user-data-dir does not remember any of the profile details like auth, cookies etc.

**Comment by Nicolas-vrcc** [comment]
Hello, same issue :p

**Comment by nicoandmee** [comment]
`  async export() {
    assert(this.page, 'page is empty');

    // eslint-disable-next-line no-underscore-dangle
    const { cookies } = (await this.page._client.send('Network.getAllCookies'));

    return new Promise(async (resolve, reject) => {
      try {
        return zlib.gzip(JSON.stringify({
          chromeUserData: (await this.getChromeUserData()).toString('base64'),
          puppeteerCookies: cookies,
          cookies: cookies.map(c => ({
            domain: c.domain,
            expires: new Date((c.expires || Date.now() / 1000) * 1000).toGMTString(),
            expiry: c.expires,
            httponly: c.httpOnly,
            name: c.name,
            path: c.path,
            secure: c.secure,
            value: c.value,
          })),
        }), (err, buf) => {
          if (err) return reject(err);
          return resolve(buf.toString('base64'));
        });
      } catch (error) {
        return reject(error);
      }
    });
  }
}`

Not sure if this will help but I use this in headless with latest puppeteer to persistently save all chrome user data/cookies/etc. Also above function references 
`async getChromeUserData() {
    assert(this.userDataDir, 'userDataDir is empty');

    try {
      const buf = await streamToBuffer(await tar.c({
        gzip: true,
        cwd: this.userDataDir,
        filter(path) {
          if (/BrowserMetrics-active\.pma$/i.test(path)) return false;
          if (/\/Favicons(-journal)?$/.test(path)) return false;
          if (/\/History(-journal)?$/.test(path)) return false;
          if (/\/Top Sites(-journal)?$/.test(path)) return false;
          if (/\/Last Session$/.test(path)) return false;
          if (/\/Last Tabs$/.test(path)) return false;
          if (/\/Visited Links$/.test(path)) return false;
          if (/\/ShaderCache\//.test(path)) return false;
          if (/\/ShaderCache$/.test(path)) return false;
          if (/\/GPUCache\//.test(path)) return false;
          if (/\/GPUCache$/.test(path)) return false;
          return true;
        },
      }, ['.']));

      return buf;
    } catch (error) {
      this.logger.error('error-getChromeUserData', {
        error,
      });
      return Buffer.from('');
    }
  }`

**Comment by getuliojr** [comment]
@nicoandmee can  you show a more specific example in how to use this function ?

**Comment by Ron-Burg** [comment]
I found a way to get around this issue!
giving the puppeteer.launch args for the userDataDir will keep it both on headless true/false.
for example, I **had issue** while using this:
`const browser = await puppeteer.launch({headless: true, userDataDir: "myDataDir")`
but when using like that:
`const path = require('path');`
``const browser = await puppeteer.launch({headless: true, args: [`--user-data-dir=${path.resolve(__dirname, 'myDataDir')}`] });``
It works perfectly 💯 (note that I had to use absolute path)

Please let me know if that works for you

**Comment by vsemozhetbyt** [comment]
@Ron-Burg Thank you. Currently, I failed to test due to https://github.com/GoogleChrome/puppeteer/issues/3452 and https://github.com/GoogleChrome/puppeteer/issues/3453 . Will try to come up with other sites.

**Comment by sarfraznawaz2005** [comment]
@Ron-Burg Awesome, it works, I also didn't use absolute path, works with relative path too.

**Comment by vsemozhetbyt** [comment]
Thank you! https://github.com/GoogleChrome/puppeteer/pull/3481 does fix this issue for me.

**Comment by sarfraznawaz2005** [comment]
For me, still does not seem to work. I used latest source of pupeteer (1.10.0) and Chrome that comes as part of this. Here is the code:

```javascript
const browser = await puppeteer.launch({
  headless: true,
  userDataDir: "./tmp",
  args: [
	'--disable-infobars',
	'--window-position=0,0',
	'--ignore-certificate-errors',
	'--ignore-certificate-errors-spki-list'
  ]
});

const page = await browser.newPage();

page.goto('https://web.whatsapp.com/', { waitUntil: 'networkidle2', timeout: 0 }).then(async function (response) {

  await page.waitFor(networkIdleTimeout);

  // do stuff
  
})
```

This works fine, site loads fine and I can do everything fine. The `tmp` user directory is also filled with stuff after running above code with `headless` set to `false`. But as soon as I set `headless` to `true` while keeping `tmp` directory intact with previous session, it just loads blank page, seems like nothing gets called after statement `const page = await browser.newPage()`.

Can anybody share what am I missing here ?

FYI, I am on Windows 10.

Thanks


`

**Comment by pswzyu** [comment]
in my experiment, userDataDir only works if I use absolute path, using a relative path will only save things related to "crashpad"? into the folder, but all others are lost

I'm using windows 10
@sarfraznawaz2005 hope this can help you

**Comment by sarfraznawaz2005** [comment]
#3490 

@pswzyu Thanks for reply. Tried using `userDataDir: "C:\\Dev\\tmp"` too but in this case, response is `<html><head></head><body></body></html>` and screen generated is white empty one.

**Comment by vsemozhetbyt** [comment]
See also https://github.com/GoogleChrome/puppeteer/issues/3453

**Comment by pswzyu** [comment]
@vsemozhetbyt thanks for sending this link. I was indeed using the bundled chromium under headless mode with a relative userDataDir. I did not pay attention to the cpu usage, but I did experience the hang. I did not know there is a connection between relative dir and the hang.

@sarfraznawaz2005 I also need to mention that after being not successful with the bundled chromium came with the puppeteer install, I switched to a chrome installed on my machine. Please try.

var chromeConfig = {
    executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
    headless: true,
    userDataDir: "C:\\xxxxxxxxxxxxxxxxx\\tmpUserProfile",
    args: [
        '--remote-debugging-port=9222',
        '--disable-gpu',
        '--disable-infobars',
        '--window-position=0,0',
        '--ignore-certificate-errors',
        '--ignore-certificate-errors-spki-list'
    ]
};

**Comment by sarfraznawaz2005** [comment]
@pswzyu In that case unfortunately it thinks it is not chrome browser even though I specified original chrome binary in `executablePath`, here is screenshot generated. Tried setting user-agent with no luck: `await page.setUserAgent('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36');`

![image](https://user-images.githubusercontent.com/201788/47961393-f39a6e80-e02b-11e8-9f73-859684696214.png)

**Comment by marqsitelabs** [comment]
@sarfraznawaz2005 Same problem here. It seems that the problem is that setUserAgent is overridden when userDataDir data is loaded

**Comment by ghost** [comment]
Was there a solution to this?

**Comment by onderceylan** [comment]
This is still an issue and it seems like providing userDataDir as launch arg does the trick: https://github.com/puppeteer/puppeteer/issues/921#issuecomment-433599870

**Comment by paragbaxi** [comment]
confirmed on mac os 10.15.1, puppeteer 2.0.0

**Comment by shirshak55** [comment]
hey guys today i found one solution to issue. persisting cookies seems to take like 60 seconds. So what i did was not closed browser for and delay 60 second. And found it works perfectly after that.

**Comment by ahvahsky2008** [comment]
Hey guys. Pls solve issue

**Comment by shirshak55** [comment]
@ahvahsky2008 whats your issue. I do see cookie being persisted properly in headless?

**Comment by lonecrane** [comment]
Confirmed on win 10 and chrome 80.0.3987.132.
Was there a solution to this?

**Comment by Vasile-Peste** [comment]
Up?

**Comment by Vasile-Peste** [comment]
> I found a way to get around this issue!
> giving the puppeteer.launch args for the userDataDir will keep it both on headless true/false.
> for example, I **had issue** while using this:
> `const browser = await puppeteer.launch({headless: true, userDataDir: "myDataDir")`
> but when using like that:
> `const path = require('path');`
> `` const browser = await puppeteer.launch({headless: true, args: [`--user-data-dir=${path.resolve(__dirname, 'myDataDir')}`] }); ``
> It works perfectly 💯 (note that I had to use absolute path)
> 
> Please let me know if that works for you

For everyone having this issue: this solution is working. Thank you!

**Comment by sydney-d** [comment]
hello @Vasile-Peste what version are you using ? 
It's not working for me, with v3

**Comment by Vasile-Peste** [comment]
> hello @Vasile-Peste what version are you using ?
> It's not working for me, with v3

2.1.1. You set the absolute path through path.resolve?

**Comment by sydney-d** [comment]
I'm downgraded to version 2 and it's working.
Cookies were lost with version 3 (and absolute path set through path.resolve)

Thanks

**Comment by Llorx** [comment]
Why is this closed?

**Comment by sathia-musso** [comment]
I'm having the same issue, any way to have it working?

**Comment by vincentheet** [comment]
I'm also seeing this issue on Windows 10. Cookies aren't persisted when running in headless mode since v2.1.0. It worked fine in v2.0.0. The issue is not present on macOS, version v2.1.1 and v3.0.2 work as expected on the mac. The fix suggested by @Ron-Burg  to set the user data dir as an argument does not work for me either. 

On thing I noticed is that when running in headless mode true the Cookies table in the Cookies file (SQLite database) stays empty. When running with headless mode false the Cookies table does get populated.

**Comment by bozdoz** [comment]
Tried every suggestion here. Can't get cookies to persist from headless to headful.  Even between headless sessions, the cookies are lost.

**Comment by Llorx** [comment]
So the solution is to revert to `v2.0.x` if headless cookies are critical to us?

**Comment by shanesreal** [comment]
I've downgraded puppeteer from v3.0.4 to v2.1.1 which didn't work and then finally downgraded to v2.0.0 and cache is now working properly in headless mode.

**Comment by peixotorms** [comment]
why is this closed?
Still not working.

**Comment by ArtixZ** [comment]
Is this issue really fixed in Chrome version `64.0.3262.0`? I still have this issue in Chrome version 84.

Tried in Windows 10. userDataDir with headless doesn't store my login session.

**Comment by rubengmurray** [comment]
I'm adding this for reference as a few people have mentioned macOS in this thread: I've been able to use cookies for a couple of years without issue in puppeteer using the `chrome-cookies-secure` npm package.

**Comment by fatmalama** [comment]
workaround? (not cookies but whole user profile, including localstorage)
it is definitely not fixed. maybe a regression. really terrible in any case

**Comment by marqsitelabs** [comment]
Hi,

I had this problem about 1 year and a half ago and I submitted a comment in this thread. The same problem was happening to me a month ago and the solution I found was including the full path in the `userDataDir` parameter.

Example:

```
const browser = await puppeteer.launch({
	userDataDir: '/var/www/html/nodetest/whateverfolder',
	headless: true,
	args: ['--no-sandbox']
});
```

**Comment by kajojify** [comment]
Hello guys. Still face this on Chrome 85.0.4183.121 (Official Build) (64-bit) for Windows 10.

**Comment by Zogoo** [comment]
Is this issue solved or still pending? Because, it's still happening on v5.4.0

**Comment by shirshak55** [comment]
I just use playwright and there is no such issue + playwright is maintained by original authors. This issue will probably never be fixed because I don't see same progress in puppeteer as it used to be.

**Comment by anaskasmi** [comment]
I can't believe This issue is still persisting since 2017 and it is almost 2021 :/
 puppeteer: "^5.3.1",
 version of Chromium  :  86.0.4240.0 (Developer Build) (64-bit)
 OS : Windows 10 Pro

**Comment by coelho-faminto** [comment]
This is not a "bug" really.
The developers could have fixed this long ago but they wont. That is because saved sessions can defeat google recaptcha ;)

The only way to fix that is by recompiling chromium, this is not a puppeteer issue, you can easily reproduce this behavior by running the chromium/chrome command line passing --user-data-dir and --headless to confirm that when --headless is present the user-data-dir will be ignored and the sessions will not be retrieved.

This is by design...

**Comment by sathia-musso** [comment]
and this is a very lame design I must say

**Comment by coelho-faminto** [comment]
Exactly... as a malicious software developer, for me this does not represent a limitation since I can bypass it perfoming some runtime tricks on the targeted software. But for those legit users who don't have the ($) time and motivation necessary to get through this, it is just lame design, as you say.

In the end they are blocking the legit users while the malicious developers are still taking full advantage from the debugging tools :+1: 

If anyone here reading this is using chromium to defeat captcha on botnets: yay!

If you are not but you would like to you just have to think about one thing: The behavior of chromium-like browsers is completely different when --headless is enabled. So think carefully about it, all you really want is to do everything without the (victim) (client) user seeing anything. You don't need headless... Keep your software away from this option and you will be fine.

**Comment by ggmoritz** [comment]
So any solution for the C# bindings? Except using firefox instead? :p

**Comment by fatmalama** [comment]
@H4xX0r1337 the solution is use playwright. it works and is much better documented

**Comment by shirshak55** [comment]
@mikelpr yea people complaining here are too lazy to even switch package.  Just use playwright and be happy? It has even python, c# bindings etc.

**Comment by ggmoritz** [comment]
@mikelpr @shirshak55 ayy thanks, that that looks very cool as well. It also looks more modern and the async API would be another pro. Although it is much less known than selenium.

**Comment by r-ti** [comment]
Olá, estamos em 2022, não sei se foi resolvido de outra forma. Mas resolvi usando a biblioteca puppeteer-firefox:

//npm i puppeteer-firefox

const puppeteerFirefox = require('puppeteer-firefox');

let browser = await puppeteerFirefox.launch({ 
     headless: true,
     args: ['--no-zygote', '--no-sandbox'],
     defaultViewport: null, 
     userDataDir: DATA_PATH,
    //browser: 'chromium',
});

Depois setei:
page.setUserAgent("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36");

Até mais...

**Comment by rainb3rry** [comment]
Still have same problem as https://stackoverflow.com/questions/73092900/how-to-keep-current-browser-data-on-headlesstrue-mode-in-puppeteer
