### ISSUE TITLE
[Bug]: Error with selector including `:not()`

### ISSUE THREAD

**Issue by ProchaLu** [puppeteer/puppeteer#9828]
### Bug expectation

I expect the selector `'[data-test-id^="test-"]:not([data-test-id^="test-foo"])'` to select all elements with a `'data-test-id'` attribute starting with "test-", except for those with the suffix "-foo".

Since updating to Puppeteer-core 19.7.3, the selector `'[data-test-id^="test-"]:not([data-test-id^="test-foo"])'` is no longer recognized as a valid selector, and I receive the following error message:
```
Error: Evaluation failed: Error: [data-test-id^="test-"]:not([data-test-id^="test-foo"]) is not a valid selector: Unexpected sequence
```

Downgrading to version 19.7.2 of Puppeteer allows the selector `'[data-test-id^="test-"]:not([data-test-id^="test-foo"])'` to function as expected

### Bug behavior

- [ ] Flaky
- [ ] PDF

### Minimal, reproducible example

```TypeScript
import { launch } from 'puppeteer';

(async () => {
  const browser = await launch();
  const page = await browser.newPage();

  await page.goto('https://example.com');

  await page.$$(
    '[data-test-id^="test-"]:not([data-test-id^="test-foo"])',
  );

  await browser.close();
})();
```

### Error string

`Error: Evaluation failed: Error: [data-test-id^="test-"]:not([data-test-id^="test-foo"]) is not a valid selector: Unexpected sequence )`

### Puppeteer version

19.7.3

### Node version

18.13.0

### Package manager

yarn

### Package manager version

1.22.19

### Operating system

macOS

**Comment by dangmai** [comment]
I'm running into the same issue as well. In my case the selector is `input[value='Search']:not([class='hidden'])`.

This only shows up in 19.7.3

**Comment by OrKoN** [comment]
Thanks for reporting this! We are working on some refactoring for the selector support and looks like this is an unexpected regression. Please use the working version for now.

**Comment by jrandolf** [comment]
This will be fixed in the next release.

**Comment by OrKoN** [comment]
Fixed in 19.7.5

**Comment by andersk** [comment]
Still an issue in 19.7.5 with the selector `.user_row[data-user-id="\38 "]:not(.deactivated_user)`:

```
Page error: Error: .user_row[data-user-id="\38 "]:not(.deactivated_user) is not a valid selector: Unexpected sequence ( found at index 34
```

**Comment by OrKoN** [comment]
@andersk thanks for the example! It appears fixed on main (and we plan to release soon). I am adding test cases from the issue to https://github.com/puppeteer/puppeteer/pull/9875 to make sure we have the coverage.
